### ISSUE TITLE
use a language attribute on the html tag

### ISSUE THREAD

**Issue by marado** [marado/kokori#28]
https://www.w3.org/International/questions/qa-html-language-declarations

**Comment by BenDiuguid** [comment]
I'll take this.

I took a quick look, and I should only need to change `flickr.html`?

And is it a correct assumption to assume `lang="en"`?

**Comment by marado** [comment]
- at least the main page doesn't have the lang/xml:lang tags;
- yes, you can assume English

Thanks!

**Comment by BenDiuguid** [comment]
The PR is up https://github.com/marado/kokori/pull/29

We can discuss any changes there? 😄

**Comment by marado** [comment]
The PR did exactly what I wanted, thank you!
